content = open('index.html','r',encoding='utf-8').read()
idx = content.find('showPage')
print(content[idx-50:idx+200])
idx2 = content.find('id="home"')
print('home:', idx2)
idx3 = content.find('id="bestxi"')
print('bestxi:', idx3)
idx4 = content.find('vue quiz')
print('vue quiz:', idx4)
idx5 = content.find('Vue quiz')
print('Vue quiz:', idx5)
