content = open('index.html','r',encoding='utf-8').read()
idx = content.find("var quizData")
print('quizData position:', idx)
idx2 = content.find("startQuiz")
print('startQuiz position:', idx2)
idx3 = content.find("chaouat")
print('chaouat position:', idx3)
