content = open('index.html','r',encoding='utf-8').read()
content = content.replace('HANSI FLICK', 'PEP GUARDIOLA')
content = content.replace('Hansi Flick', 'Pep Guardiola')
content = content.replace('"Barcelona"', '"Manchester City"')
content = content.replace("'Barcelona'", "'Manchester City'")
content = content.replace('"de Allemagne"', '"es Espagne"')
content = content.replace("'de Allemagne'", "'es Espagne'")
open('index.html','w',encoding='utf-8').write(content)
print('OK')
